# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: "pnpm"
      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
      - name: Building
        run: pnpm build ${{ vars.PUBLISH_FILTER }}
      - name: Publishing
        run: pnpm publish --access public --no-git-checks ${{ vars.PUBLISH_FILTER }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
